gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Gitea
      hajimari.io/icon: git
    hosts:
      - host: &host git.172-28-0-3.nip.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.172-28-0-3.nip.io
  persistence:
    storageClass: local-path
  postgresql:
    persistence:
      storageClass: local-path
